fileVersion: 1
id: "2"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: ROB_EDW
    schema: PREVIEWQAONLY_ENV
name: Main Environment
type: Environment
